global:
  scrape_interval: 5s  # 기본 수집 주기 (5초)
  evaluation_interval: 5s  # 규칙을 평가하는 주기

scrape_configs:
  - job_name: 'jobbotdari'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['jobbotdari:8081']

  - job_name: 'jobbotdari-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['jobbotdari-user:8080' ]

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8070']

  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-server:8072']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']